language: node_js

node_js:
  - "8"
  - "10"

sudo: false

script:
  - npm run lint
  - npm run test

# Don't build pushes to branches other than our deploy branches. (This doesn't
# affect PR builds, which are separate from branch builds in Travis. If we
# didn't have this config, Travis would run both types of builds for PRs,
# consuming our concurrent builds.)
branches:
  only:
    - master
